#!/bin/bash

set -e   # bail on error

################################################################################
# create directories
################################################################################

# create directory for control plane component configuration
install -d -m 755 /etc/kubernetes/config

# create directory for control plane certs, keys, kubeconfigs and configs
install -d -m 755 /var/lib/kubernetes

################################################################################
# install control plane components
################################################################################

# install control plane binaries
install -m 755 kube-apiserver          /usr/local/bin/kube-apiserver
install -m 755 kube-controller-manager /usr/local/bin/kube-controller-manager
install -m 755 kube-scheduler          /usr/local/bin/kube-scheduler
install -m 755 kubectl                 /usr/local/bin/kubectl

# install CA cert and key
install -m 644 ca.crt /var/lib/kubernetes/ca.crt
install -m 600 ca.key /var/lib/kubernetes/ca.key

# install kube-apiserver TLS cert and key
install -m 644 kube-api-server.crt /var/lib/kubernetes/kube-api-server.crt
install -m 600 kube-api-server.key /var/lib/kubernetes/kube-api-server.key

# install service account signing cert and key
install -m 644 service-accounts.crt /var/lib/kubernetes/service-accounts.crt
install -m 600 service-accounts.key /var/lib/kubernetes/service-accounts.key

# install data encryption config
install -m 600 encryption-config.yaml /var/lib/kubernetes/encryption-config.yaml

# install kubeconfigs
install -m 644 kube-controller-manager.kubeconfig /var/lib/kubernetes/kube-controller-manager.kubeconfig
install -m 644 kube-scheduler.kubeconfig /var/lib/kubernetes/kube-scheduler.kubeconfig

# install kube-scheduler configuration
install -m 644 kube-scheduler.yaml /etc/kubernetes/config/kube-scheduler.yaml


# install systemd unit files
install -m 644 kube-apiserver.service          /etc/systemd/system/
install -m 644 kube-controller-manager.service /etc/systemd/system/
install -m 644 kube-scheduler.service          /etc/systemd/system/

# reload systemd
systemctl daemon-reload

# enable services
systemctl enable kube-apiserver
systemctl enable kube-controller-manager
systemctl enable kube-scheduler

# start services
systemctl start kube-apiserver
systemctl start kube-controller-manager
systemctl start kube-scheduler